### ISSUE TITLE
Issue Template?

### ISSUE THREAD

**Issue by dvlden** [dracondev/simple.css#49]
Where did issue template disappear? I don't see it in `.git` anymore.

**Comment by cpdevelops** [comment]
The issue template was an accidental clone of the pull request template. I deleted it because of that.

If you would like me to create an issue template than please let me know and I will go ahead and do so.

**Comment by dvlden** [comment]
Would be nice to have a nice template but make things optional and clear, because many issues might not have all of the required fields of the template...

**Comment by dracondev** [comment]
Coming back to this project a little bit. Just added some new templates through Github's new templates feature for bug and feature reports.
